spring:
  datasource:
    url: jdbc:postgresql://${TWITTER_DB_HOST}:5433/${TWITTER_DB_NAME}
    username: ${TWITTER_DB_USERNAME}
    password: ${TWITTER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
